### ISSUE TITLE
Scripts manquant

### ISSUE THREAD

**Issue by bbabou** [Korioz/krz_gangsbuilder#1]
Bonjour,

J'ai installé tous les scripts indiqués "nécessaires" mais les gangs ne marchent pas

**Comment by GeKOfficiel** [comment]
Salut, sa viens du nouveau extended si tu la mis a jours... Faut attendre que @Korioz le mette à jours

**Comment by bbabou** [comment]
ok merci @GeKOfficiel

**Comment by Korioz** [comment]
Ils ont foutu quoi encore esx 😑

**Comment by GeKOfficiel** [comment]
@Korioz Devine encore de la merde haha

**Comment by bbabou** [comment]
ok ca sera fix ?
Quel script de double job est nécessaire aussi svp ?

**Comment by GeKOfficiel** [comment]
@jadou7 Il faut que tu le créer toi dans le es_extended, il y a plusieurs ligne a faire. Je pense sur internet tu trouvera.
