### ISSUE TITLE
Problème Gang

### ISSUE THREAD

**Issue by nathandevdufivem** [Korioz/krz_gangsbuilder#7]
Bonjour,
J'ai installé le gangs builder, tout fonctionne sauf une chose ;
Quand je fouille une autre personne je peux la fouiller sans que cette personne lève les mains et j'aimerais que les gangs puissent fouiller uniquement si l'autre lève les mains ! ( sinon les gangs deviennent des lspd au niveau fouiller ^^ )
J'espère que vous pourrez m'aider. 
Merci d'avance

**Comment by Korioz** [comment]
Je vois pas en quoi c'est un problème en lien avec mon script
